title: City Management
description: This website is a project we proudly crafted during our 3rd semester for the Design and Analysis of Algorithms course—where logic meets creativity! 🚀
theme: jekyll-theme-cayman 
